// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallRcloneAPI(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CallRcloneAPI'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function GetInstances() {
  return window['go']['main']['App']['GetInstances']();
}

export function RestartInstance(arg1) {
  return window['go']['main']['App']['RestartInstance'](arg1);
}

export function SaveInstance(arg1) {
  return window['go']['main']['App']['SaveInstance'](arg1);
}

export function StartInstance(arg1) {
  return window['go']['main']['App']['StartInstance'](arg1);
}

export function StopInstance(arg1) {
  return window['go']['main']['App']['StopInstance'](arg1);
}
