// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CallRcloneAPI(arg1:string,arg2:any,arg3:string,arg4:string,arg5:string,arg6:string):Promise<any>;

export function DeleteInstance(arg1:string):Promise<void>;

export function GetInstances():Promise<Array<main.Instance>>;

export function RestartInstance(arg1:string):Promise<void>;

export function SaveInstance(arg1:main.Instance):Promise<void>;

export function StartInstance(arg1:string):Promise<void>;

export function StopInstance(arg1:string):Promise<void>;
